name: Announce release on Slack

on:
  # Triggers the workflow on new release
    release:
      types: [ published ]

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: adamkdean/simple-slack-notify@master
      with:
        fields: |
          [{ "title": "Repository", "value": "${env.GITHUB_REPOSITORY}", "short": true },
                 { "title": "Branch", "value": "${env.BRANCH}", "short": true }]
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
